server:
  port: 8003

# 日志文件配置
logging:
  config: classpath:logback.xml
  level: info

# 系统默认的重置密码
defaultPassword: 123456

# 默认目标系统为 统一权限管理系统
defaultTargetAppCode: UnifyAuthorityManagement

# 统一权限管理系统 管理员角色编码
uamAdminRoleCode: uam_admin

# thymeleaf地址前缀
spring.thymeleaf.prefix=classpath: /templates/

# 设置session存储类型为redis
spring:
  session:
    store-type: redis

# session的过期时间，单位是分钟   1440表示1天
sessiontimeout: 1440

# cookie的过期时间，单位是秒  86400表示1天
cookietimeout: 86400

# 配置redis连接信息
spring.redis:
    # host: 192.168.13.118
    # port: 6379
    # password: 1qaz!QAZ
    database: 0
    pool:
      max-idle: 10
      max-total: 50
      max-wait-millis: -1
    sentinel:
      master: mymaster  # name of Redis server  哨兵监听的Redis server的名称  
      nodes: localhost:27000 #  comma-separated list of host:port pairs  哨兵的配置列表  

#spring的数据源配置
spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  jdbcUrl: jdbc:mysql://localhost:3306/mars_uam
  username: root
  password: 1qaz!QAZ
  driverClassName: com.mysql.jdbc.Driver
  #配置数据库连接池HikariCP
  maximum-pool-size: 50
  maximum-idle: 50
  minimum-idle: 20

spring.jpa:
  database: mysql
  show-sql: true
  hibernate.ddl-auto: update
  hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# 注册中心配置
spring.application.name: mars_uam
# 应用程序实例显示真实ip地址
eureka.instance.preferIpAddress: true
# 配置注册中心集群
eureka.client.service-url.defaultZone: http://localhost:8001/eureka

# RestTemplate配置
restTemplateConfig:
  maxTotal: 100
  maxPerRoute: 30
  retryCount: 1
  connectTimeout: 30000
  readTimeout: 120000
  connectionRequestTimeout: 30000

productSystemRootUrl: http://www.baidu.com
